title: Personalized Website
author: Kalpana Joshi
theme: minima
email: kjoshi@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 This is my website. Thanks so much for viewing! Don't forget
 to follow my social media, and text me for more. This has
 been AP Computer Science Application, signing out! :)

# social links
instagram_username: kjxshi
github_username:  kjxshi

show_excerpts: true # set to false to remove excerpts on the homepage
